# Generated by Django 5.1.15 on 2026-08-17 16:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text="Short code, e.g. 'DLVRY'", max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=60)),
                ('invoice_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('RECONCILED', 'Reconciled'), ('DISPUTED', 'Disputed'), ('CLOSED', 'Closed')], default='UPLOADED', max_length=12)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reconciliation.courier')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(db_index=True, max_length=50)),
                ('billed_zone', models.CharField(blank=True, choices=[('A', 'Zone A - Intra-city'), ('B', 'Zone B - Intra-state'), ('C', 'Zone C - Metro to metro'), ('D', 'Zone D - Rest of India'), ('E', 'Zone E - Special (NE, J&K, islands)')], max_length=1)),
                ('billed_weight_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Computed by the reconciler from the rate card.', max_digits=10, null=True)),
                ('row_number', models.PositiveIntegerField(default=0, help_text='Source row in the uploaded CSV, for traceability.')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reconciliation.courierinvoice')),
            ],
            options={
                'ordering': ['row_number', 'awb'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('WEIGHT', 'Weight mismatch'), ('ZONE', 'Zone mismatch'), ('RATE', 'Rate applied incorrectly'), ('DUPLICATE', 'Duplicate AWB billed'), ('UNKNOWN_AWB', 'AWB not in our system'), ('NO_RATE_CARD', 'No rate card covers this date')], max_length=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISPUTED', 'Raised with courier'), ('RECOVERED', 'Credit note received'), ('WAIVED', 'Waived internally')], default='OPEN', max_length=10)),
                ('detail', models.TextField(help_text='Human-readable explanation for the dispute email.')),
                ('amount_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive = courier overcharged us.', max_digits=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='reconciliation.invoiceline')),
            ],
            options={
                'verbose_name_plural': 'discrepancies',
                'ordering': ['-amount_impact'],
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank while this card is current.', null=True)),
                ('volumetric_divisor', models.PositiveIntegerField(default=5000, help_text='cm3 per kg. Industry standard is 5000.')),
                ('fuel_surcharge_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage applied on top of freight.', max_digits=5)),
                ('cod_fee_flat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('cod_fee_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent of order value. The higher of flat/pct applies.', max_digits=5)),
                ('rto_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Return leg cost as a multiple of forward freight.', max_digits=4)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='reconciliation.courier')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RateSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('A', 'Zone A - Intra-city'), ('B', 'Zone B - Intra-state'), ('C', 'Zone C - Metro to metro'), ('D', 'Zone D - Rest of India'), ('E', 'Zone E - Special (NE, J&K, islands)')], max_length=1)),
                ('base_weight_kg', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('increment_weight_kg', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('increment_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='reconciliation.ratecard')),
            ],
            options={
                'ordering': ['zone'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(db_index=True, help_text='Air waybill / tracking number. The join key against courier invoices.', max_length=50, unique=True, verbose_name='AWB number')),
                ('order_ref', models.CharField(db_index=True, max_length=50)),
                ('zone', models.CharField(choices=[('A', 'Zone A - Intra-city'), ('B', 'Zone B - Intra-state'), ('C', 'Zone C - Metro to metro'), ('D', 'Zone D - Rest of India'), ('E', 'Zone E - Special (NE, J&K, islands)')], max_length=1)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('RTO', 'Returned to origin'), ('LOST', 'Lost / damaged')], default='IN_TRANSIT', max_length=12)),
                ('payment_mode', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on delivery')], default='PREPAID', max_length=8)),
                ('order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_weight_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('length_cm', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('shipped_on', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='reconciliation.courier')),
            ],
            options={
                'ordering': ['-shipped_on', 'awb'],
            },
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='reconciliation.shipment'),
        ),
        migrations.AddConstraint(
            model_name='courierinvoice',
            constraint=models.UniqueConstraint(fields=('courier', 'invoice_number'), name='unique_invoice_per_courier'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['kind', 'status'], name='disc_kind_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratecard',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ratecard_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='rateslab',
            constraint=models.UniqueConstraint(fields=('rate_card', 'zone'), name='unique_zone_per_rate_card'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['courier', 'shipped_on'], name='ship_courier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['zone', 'status'], name='ship_zone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'awb'], name='line_invoice_awb_idx'),
        ),
    ]
